config.yaml: |
  site:
    host: localhost:7143
    domain: localhost
    ssl: false
    secret: 'CHANGE_THIS_SECRET'
  redis:
    host: redis.redis.svc.cluster.local
    port: 6379
    db: 0
    password: 'redis'
  development:
    adapter: redis
    connection:
      host: redis.redis.svc.cluster.local
      port: 6379
      password: 'redis'
      db: 0
  production:
    adapter: redis
    connection:
      host: redis.redis.svc.cluster.local
      port: 6379
      password: 'redis'
      db: 0