apiVersion: source.toolkit.fluxcd.io/v2
kind: OCIRepository
metadata:
  name: redis-chart
  namespace: flux-system
spec:
  interval: 1h
  url: oci://registry-1.docker.io/bitnamicharts/redis
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
  ref:
    tag: "20.11.4"  