apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: redis
  namespace: flux-system
spec:
  releaseName: redis
  targetNamespace: redis
  interval: 5m
  chart:
    spec:
      chart: redis
      version: '17.10.0'
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    auth:
      enabled: true
      password: "redis-password"  # In production, use SecretProviderClass
    master:
      persistence:
        enabled: true
        size: 1Gi