apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: redis
  namespace: flux-system
spec:
  releaseName: redis
  targetNamespace: redis
  interval: 5m
  chart:
    spec:
      chart: redis
      sourceRef:
        kind: OCIRepository
        name: redis-chart
        namespace: flux-system
  values:
    auth:
      enabled: true
      password: "redis-password"
    master:
      persistence:
        enabled: true
        size: 1Gi