apiVersion: v1
kind: Service
metadata:
  name: nexus-docker
  namespace: nexus
spec:
  selector:
    app.kubernetes.io/component: repository
    app.kubernetes.io/instance: nexus
    app.kubernetes.io/name: nexus3
  ports:
  - port: 5000
    targetPort: 5000
    name: docker
  type: ClusterIP