apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nexus
  namespace: flux-system
spec:
  releaseName: nexus
  targetNamespace: nexus
  interval: 5m
  chart:
    spec:
      chart: nexus3
      version: '5.9.1'
      sourceRef:
        kind: HelmRepository
        name: stevehipwell
        namespace: flux-system
  values:
    service:
      type: ClusterIP
    persistence:
      enabled: true
      storageSize: 8Gi
    nexus:
      docker:
        enabled: true
        port: 5003
      resources:
        requests:
          cpu: "500m"
          memory: "1Gi"
        limits:
          cpu: "1000m"
          memory: "2Gi"