apiVersion: apps/v1
kind: Deployment
metadata:
  name: onetimesecret
  namespace: onetimesecret
spec:
  replicas: 1
  selector:
    matchLabels:
      app: onetimesecret
  template:
    metadata:
      labels:
        app: onetimesecret
    spec:
      containers:
      - name: onetimesecret
        image: nexus-docker.nexus.svc.cluster.local:5000
        ports:
        - containerPort: 7143
        env:
        - name: RACK_ENV
          value: development
        - name: RAILS_ENV
          value: development
        - name: REDIS_URL
          value: redis://:$(REDIS_PASSWORD)@redis.redis.svc.cluster.local:6379/0
        envFrom:
        - secretRef:
            name: redis-secret
      imagePullSecrets:
      - name: regcred