apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: nexus-credentials
  namespace: onetimesecret
spec:
  refreshInterval: "15m"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: regcred
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |
          {
            "auths": {
              "{{ .nexusUrl }}": {
                "username": "{{ .username }}",
                "password": "{{ .password }}",
                "auth": "{{ list .username .password | join \":\" | b64enc }}"
              }
            }
          }
  data:
  - secretKey: username
    remoteRef:
      key: nexus
      property: username
  - secretKey: password
    remoteRef:
      key: nexus
      property: password
  - secretKey: nexusUrl
    remoteRef:
      key: nexus
      property: url
      conversionStrategy: Default
      decodingStrategy: None